### ISSUE TITLE
New point release

### ISSUE THREAD

**Issue by jrgarcia** [zk-ruby/zk-server#9]
We are encountering problems with this gem and #8 fixes the issue for us (due to using zk 1.9.6). Are there any plans to release a new version with this fix included?

**Comment by Suirtimed** [comment]
:+1:

**Comment by slyphon** [comment]
Yes, I'm currently finishing up the last of the Jewish holidays and should be able to do a release shortly

--
Jonathan Simms
(sent from my mobile device)

**Comment by jrgarcia** [comment]
Thanks!

**Comment by slyphon** [comment]
hey sorry I derped out and just cut the release manually (rather than merging this)

the version is 1.1.8, please let me know if it works for you guys.

**Comment by lukaszx0** [comment]
@slyphon I've updated and tested it on 3 different zk-based libs - everything is green. Thanks!

**Comment by jrgarcia** [comment]
@slyphon This got us past the issues we were having. Thanks for bumping the version! @lukaszx0 Thanks for the original commit that fixes it!
